from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision='0001_initial'; down_revision=None; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('users',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('username',sa.String(64),nullable=False,unique=True),sa.Column('password_hash',sa.String(256),nullable=False),sa.Column('role',sa.String(16),nullable=False,server_default='LEARNER'),sa.Column('is_active',sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_index('ix_users_username','users',['username'])
    op.create_table('knowledge_items',sa.Column('id',sa.String(100),primary_key=True),sa.Column('type',sa.String(32),nullable=False),sa.Column('title_vi',sa.String(300),nullable=False),sa.Column('title_en',sa.String(300),nullable=False),sa.Column('summary_vi',sa.Text(),nullable=False),sa.Column('summary_en',sa.Text(),nullable=False),sa.Column('definition_vi',sa.Text(),nullable=False),sa.Column('definition_en',sa.Text(),nullable=False),sa.Column('chapter_id',sa.String(100),nullable=False),sa.Column('tags',sa.JSON(),nullable=False),sa.Column('syntax',sa.Text()))
    op.create_index('ix_knowledge_items_type','knowledge_items',['type']); op.create_index('ix_knowledge_items_chapter_id','knowledge_items',['chapter_id'])
    op.create_table('knowledge_relations',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('source_id',sa.String(100),sa.ForeignKey('knowledge_items.id',ondelete='CASCADE'),nullable=False),sa.Column('target_id',sa.String(100),sa.ForeignKey('knowledge_items.id',ondelete='CASCADE'),nullable=False),sa.Column('relation_type',sa.String(32),nullable=False),sa.Column('weight',sa.Integer(),nullable=False,server_default='1'),sa.Column('is_active',sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column('metadata',sa.JSON(),nullable=False),sa.UniqueConstraint('source_id','target_id','relation_type'))
    op.create_index('ix_knowledge_relations_source_id','knowledge_relations',['source_id']); op.create_index('ix_knowledge_relations_target_id','knowledge_relations',['target_id']); op.create_index('ix_knowledge_relations_relation_type','knowledge_relations',['relation_type'])
    op.create_table('exercises',sa.Column('id',sa.String(100),primary_key=True),sa.Column('title_vi',sa.String(300),nullable=False),sa.Column('title_en',sa.String(300),nullable=False),sa.Column('statement_vi',sa.Text(),nullable=False),sa.Column('statement_en',sa.Text(),nullable=False),sa.Column('difficulty',sa.String(16),nullable=False),sa.Column('tags',sa.JSON(),nullable=False),sa.Column('patterns',sa.JSON(),nullable=False),sa.Column('required_knowledge',sa.JSON(),nullable=False),sa.Column('strategy',sa.JSON(),nullable=False),sa.Column('pseudocode',sa.JSON(),nullable=False),sa.Column('hints',sa.JSON(),nullable=False),sa.Column('solution',sa.Text(),nullable=False),sa.Column('mistakes',sa.JSON(),nullable=False),sa.Column('visualization_id',sa.String(100)),sa.Column('related_exercises',sa.JSON(),nullable=False))
    op.create_table('user_progress',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('user_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('entity_type',sa.String(32),nullable=False),sa.Column('entity_id',sa.String(100),nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('score',sa.Integer()),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint('user_id','entity_type','entity_id'))
    op.create_index('ix_user_progress_user_id','user_progress',['user_id'])

def downgrade():
    op.drop_table('user_progress'); op.drop_table('exercises'); op.drop_table('knowledge_relations'); op.drop_table('knowledge_items'); op.drop_index('ix_users_username',table_name='users'); op.drop_table('users')
