KNOWLEDGE = [
    dict(id='variable', type='CONCEPT', title_vi='Biến', title_en='Variable', summary_vi='Nơi lưu một giá trị có thể thay đổi.', summary_en='A named place that stores a changeable value.', definition_vi='Biến là tên gắn với một vùng nhớ dùng để lưu dữ liệu.', definition_en='A variable is a name bound to memory that stores data.', chapter_id='variables', tags=['variable','biến','memory'], syntax='int age = 18;'),
    dict(id='array', type='CONCEPT', title_vi='Mảng', title_en='Array', summary_vi='Tập hợp phần tử cùng kiểu, truy cập bằng chỉ số.', summary_en='A fixed-size collection of same-type values accessed by index.', definition_vi='Mảng lưu nhiều giá trị cùng kiểu và chỉ số bắt đầu từ 0.', definition_en='An array stores same-type values with zero-based indexes.', chapter_id='arrays', tags=['array','mảng','index'], syntax='int a[] = {3, 1, 5, 2};'),
    dict(id='loop', type='CONCEPT', title_vi='Vòng lặp', title_en='Loop', summary_vi='Lặp lại một nhóm lệnh theo điều kiện.', summary_en='Repeats a group of statements while a condition is met.', definition_vi='Vòng lặp giúp thực hiện cùng một thao tác trên nhiều dữ liệu.', definition_en='A loop repeats an operation over data.', chapter_id='loops', tags=['loop','vòng lặp','for','while'], syntax='for (int i = 0; i < n; i++) { }'),
    dict(id='comparison', type='RULE', title_vi='So sánh', title_en='Comparison', summary_vi='Đối chiếu hai giá trị để nhận true hoặc false.', summary_en='Compares two values and produces true or false.', definition_vi='Các toán tử >, <, >=, <=, ==, != tạo biểu thức logic.', definition_en='Comparison operators create boolean expressions.', chapter_id='operators', tags=['comparison','so sánh','operator'], syntax='current > best'),
    dict(id='linear-scan', type='PATTERN', title_vi='Duyệt tuyến tính', title_en='Linear Scan', summary_vi='Duyệt từng phần tử theo thứ tự một lần.', summary_en='Visit each element in order, usually once.', definition_vi='Cách giải đơn giản cho dữ liệu chưa sắp xếp.', definition_en='A simple approach for unsorted data.', chapter_id='algorithms', tags=['linear scan','duyệt','array']),
    dict(id='maintain-best', type='PATTERN', title_vi='Duy trì ứng viên tốt nhất', title_en='Maintain Best Candidate', summary_vi='Giữ lại giá trị tốt nhất đã thấy khi duyệt.', summary_en='Keep the best value seen while traversing.', definition_vi='Khởi tạo ứng viên từ dữ liệu thật rồi cập nhật khi gặp phần tử tốt hơn.', definition_en='Initialize from real data and update on better elements.', chapter_id='algorithms', tags=['max','min','best candidate']),
    dict(id='accumulator', type='PATTERN', title_vi='Biến tích lũy', title_en='Accumulator', summary_vi='Cộng dồn kết quả qua từng phần tử.', summary_en='Build a result progressively as elements are visited.', definition_vi='Phù hợp với tổng, tích hoặc kết quả cập nhật tuần tự.', definition_en='Fits sums, products, and progressive results.', chapter_id='algorithms', tags=['sum','accumulator']),
    dict(id='find-max', type='ALGORITHM', title_vi='Tìm số lớn nhất trong mảng', title_en='Find the maximum in an array', summary_vi='Tìm phần tử lớn nhất bằng một lần duyệt.', summary_en='Find the largest element with one scan.', definition_vi='Chọn phần tử đầu tiên làm max rồi so sánh phần còn lại.', definition_en='Choose the first element as max and compare the rest.', chapter_id='algorithms', tags=['max','tìm max','mảng','largest'], syntax='int maxValue = a[0];'),
    dict(id='find-min', type='ALGORITHM', title_vi='Tìm số nhỏ nhất trong mảng', title_en='Find the minimum in an array', summary_vi='Biến thể đối xứng của bài tìm max.', summary_en='The symmetric variant of finding a maximum.', definition_vi='Duy trì giá trị nhỏ nhất đã thấy.', definition_en='Maintain the smallest value seen.', chapter_id='algorithms', tags=['min','tìm min','mảng']),
    dict(id='linear-search', type='ALGORITHM', title_vi='Tìm kiếm tuyến tính', title_en='Linear search', summary_vi='Tìm vị trí đầu tiên của một giá trị.', summary_en='Find the first position of a value by scanning.', definition_vi='So sánh từng phần tử với giá trị cần tìm.', definition_en='Compare each element with the target.', chapter_id='algorithms', tags=['search','tìm kiếm','linear']),
    dict(id='bubble-sort', type='ALGORITHM', title_vi='Sắp xếp nổi bọt', title_en='Bubble sort', summary_vi='Đổi chỗ cặp kề nhau để đưa phần tử lớn về cuối.', summary_en='Swap adjacent pairs to move large values to the end.', definition_vi='Mỗi lượt đưa một phần tử lớn về đúng vị trí.', definition_en='Each pass places a large value in its final position.', chapter_id='algorithms', tags=['sort','sắp xếp','bubble']),
    dict(id='off-by-one', type='COMMON_MISTAKE', title_vi='Lỗi lệch một vị trí', title_en='Off-by-one error', summary_vi='Sai cận lặp khiến bỏ sót hoặc vượt phạm vi.', summary_en='A boundary error that skips or oversteps a value.', definition_vi='Với n phần tử, index cuối là n - 1.', definition_en='For n elements, the last index is n - 1.', chapter_id='loops', tags=['mistake','loop','index']),
]
RELATIONS = [
    dict(source_id='variable',target_id='array',relation_type='PREREQUISITE'), dict(source_id='array',target_id='find-max',relation_type='REQUIRES'), dict(source_id='loop',target_id='find-max',relation_type='REQUIRES'), dict(source_id='comparison',target_id='find-max',relation_type='REQUIRES'), dict(source_id='linear-scan',target_id='find-max',relation_type='PATTERN'), dict(source_id='maintain-best',target_id='find-max',relation_type='PATTERN'), dict(source_id='find-max',target_id='find-min',relation_type='SIMILAR'), dict(source_id='find-max',target_id='linear-search',relation_type='RELATED'), dict(source_id='find-max',target_id='off-by-one',relation_type='COMMON_MISTAKE'), dict(source_id='find-max',target_id='find-min',relation_type='NEXT'), dict(source_id='loop',target_id='bubble-sort',relation_type='REQUIRES'), dict(source_id='array',target_id='bubble-sort',relation_type='REQUIRES'), dict(source_id='comparison',target_id='bubble-sort',relation_type='REQUIRES'), dict(source_id='accumulator',target_id='find-max',relation_type='RELATED')
]
EXERCISES = [
    dict(id='exercise-find-max', title_vi='Tìm giá trị lớn nhất', title_en='Find the maximum', statement_vi='Cho n số nguyên, hãy in ra giá trị lớn nhất trong mảng.', statement_en='Given n integers, print the largest value in the array.', difficulty='BEGINNER', tags=['array','max','scan'], patterns=['maintain-best','linear-scan'], required_knowledge=['variable','array','loop','comparison'], strategy=[{'vi':'Chọn phần tử đầu tiên làm ứng viên max.','en':'Choose the first element as the max candidate.'}], pseudocode=['max ← a[0]','scan remaining elements','update when current > max'], hints=[{'vi':'Đừng khởi tạo max = 0 vì mọi số có thể âm.','en':'Do not initialize max = 0 because values may be negative.'},{'vi':'Dùng phần tử đầu tiên làm ứng viên.','en':'Use the first element as candidate.'},{'vi':'So sánh a[i] với max từ i = 1.','en':'Compare a[i] with max from i = 1.'}], solution='int maxValue = a[0];\nfor (int i = 1; i < n; i++)\n  if (a[i] > maxValue) maxValue = a[i];', mistakes=[{'vi':'Khởi tạo max = 0 khi input toàn âm.','en':'Initializing max = 0 fails for all-negative input.'}], visualization_id='viz-find-max', related_exercises=['exercise-find-min']),
    dict(id='exercise-find-min', title_vi='Tìm giá trị nhỏ nhất', title_en='Find the minimum', statement_vi='Cho n số nguyên, hãy in ra giá trị nhỏ nhất.', statement_en='Given n integers, print the smallest value.', difficulty='BEGINNER', tags=['array','min'], patterns=['maintain-best'], required_knowledge=['variable','array','loop','comparison'], strategy=[{'vi':'Khởi tạo min bằng phần tử đầu tiên.','en':'Initialize min from the first element.'}], pseudocode=['min ← a[0]','scan remaining elements','update when current < min'], hints=[{'vi':'Bài này đối xứng với tìm max.','en':'This mirrors finding a maximum.'},{'vi':'Đổi dấu so sánh thành <.','en':'Use the < comparison.'},{'vi':'Giữ nguyên cách duyệt.','en':'Keep the same scan.'}], solution='int minValue = a[0];', mistakes=[], visualization_id='viz-find-max', related_exercises=['exercise-find-max'])
]
